In [1]:
# AI Fake News Detection System
## Data Preprocessing

In [2]:
# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import re
import string
import warnings

warnings.filterwarnings("ignore")

In [3]:
# Display pandas settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

## Load Dataset

In [4]:
# Load Fake News dataset
fake_df = pd.read_csv("../data/Fake.csv")

# Load Real News dataset
true_df = pd.read_csv("../data/True.csv")

print("Datasets loaded successfully.")

Datasets loaded successfully.

In [5]:
# Add labels to both datasets
fake_df["label"] = 0
true_df["label"] = 1

In [6]:
# Merge both datasets
df = pd.concat([fake_df, true_df], ignore_index=True)

print("Datasets merged successfully.")

Datasets merged successfully.

In [7]:
# Display dataset shape

print(df.shape)

(44898, 5)

In [8]:
# Display first five records

df.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’s Eve Message; This is Disturbing,"Donald Trump just couldn t wish all Americans a Happy New Year and leave it at that. Instead, he had to give a shout out to his enemies, haters and the very dishonest fake news media. The former reality show star had just one job to do and he couldn t do it. As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year, President Angry Pants tweeted. 2018 will be a great year for America! As our Country rapidly grows stronger and smarter, I want to wish all of my friends, supporters, enemies, haters, and even the very dishonest Fake News Media, a Happy and Healthy New Year. 2018 will be a great year for America! Donald J. Trump (@realDonaldTrump) December 31, 2017Trump s tweet went down about as welll as you d expect.What kind of president sends a New Year s greeting like this despicable, petty, infantile gibberish? Only Trump! His lack of decency won t even allow him to rise above the gutter long enough to wish the American citizens a happy new year! Bishop Talbert Swan (@TalbertSwan) December 31, 2017no one likes you Calvin (@calvinstowell) December 31, 2017Your impeachment would make 2018 a great year for America, but I ll also accept regaining control of Congress. Miranda Yaver (@mirandayaver) December 31, 2017Do you hear yourself talk? When you have to include that many people that hate you you have to wonder? Why do the they all hate me? Alan Sandoval (@AlanSandoval13) December 31, 2017Who uses the word Haters in a New Years wish?? Marlene (@marlene399) December 31, 2017You can t just say happy new year? Koren pollitt (@Korencarpenter) December 31, 2017Here s Trump s New Year s Eve tweet from 2016.Happy New Year to all, including to my many enemies and those who have fought me and lost so badly they just don t know what to do. Love! Donald J. Trump (@realDonaldTrump) December 31, 2016This is nothing new for Trump. He s been doing this for years.Trump has directed messages to his enemies and haters for New Year s, Easter, Thanksgiving, and the anniversary of 9/11. pic.twitter.com/4FPAe2KypA Daniel Dale (@ddale8) December 31, 2017Trump s holiday tweets are clearly not presidential.How long did he work at Hallmark before becoming President? Steven Goodine (@SGoodine) December 31, 2017He s always been like this . . . the only difference is that in the last few years, his filter has been breaking down. Roy Schulze (@thbthttt) December 31, 2017Who, apart from a teenager uses the term haters? Wendy (@WendyWhistles) December 31, 2017he s a fucking 5 year old Who Knows (@rainyday80) December 31, 2017So, to all the people who voted for this a hole thinking he would change once he got into power, you were wrong! 70-year-old men don t change and now he s a year older.Photo by Andrew Burton/Getty Images.",News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian Collusion Investigation,"House Intelligence Committee Chairman Devin Nunes is going to have a bad day. He s been under the assumption, like many of us, that the Christopher Steele-dossier was what prompted the Russia investigation so he s been lashing out at the Department of Justice and the FBI in order to protect Trump. As it happens, the dossier is not what started the investigation, according to documents obtained by the New York Times.Former Trump campaign adviser George Papadopoulos was drunk in a wine bar when he revealed knowledge of Russian opposition research on Hillary Clinton.On top of that, Papadopoulos wasn t just a covfefe boy for Trump, as his administration has alleged. He had a much larger role, but none so damning as being a drunken fool in a wine bar. Coffee boys don t help to arrange a New York meeting between Trump and President Abdel Fattah el-Sisi of Egypt two months before the election. It was known before that the former aide set up meetings with world leaders for Trump, but team Trump ran with him being merely a coffee boy.In May 2016, Papadopoulos revealed to Australian diplomat Alexander Downer that Russian officials were shopping around possible dirt on then-Democratic presidential nominee Hillary Clinton. Exactly how much Mr. Papadopoulos said that night at the Kensington Wine Rooms with the Australian, Alexander Downer, is unclear, the report states. But two months later, when leaked Democratic emails began appearing online, Australian officials passed the information about Mr. Papadopoulos to their American counterparts, according to four current and former American and foreign officials with direct knowledge of the Australians role. Papadopoulos pleaded guilty to lying to the F.B.I. and is now a cooperating witness with Special Counsel Robert Mueller s team.This isn t a presidency. It s a badly scripted reality TV show.Photo by Win McNamee/Getty Images.",News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke For Threatening To Poke People ‘In The Eye’,"On Friday, it was revealed that former Milwaukee Sheriff David Clarke, who was being considered for Homeland Security Secretary in Donald Trump s administration, has an email scandal of his own.In January, there was a brief run-in on a plane between Clarke and fellow passenger Dan Black, who he later had detained by the police for no reason whatsoever, except that maybe his feelings were hurt. Clarke messaged the police to stop Black after he deplaned, and now, a search warrant has been executed by the FBI to see the exchanges.Clarke is calling it fake news even though copies of the search warrant are on the Internet. I am UNINTIMIDATED by lib media attempts to smear and discredit me with their FAKE NEWS reports designed to silence me, the former sheriff tweeted. I will continue to poke them in the eye with a sharp stick and bitch slap these scum bags til they get it. I have been attacked by better people than them #MAGA I am UNINTIMIDATED by lib media attempts to smear and discredit me with their FAKE NEWS reports designed to silence me. I will continue to poke them in the eye with a sharp stick and bitch slap these scum bags til they get it. I have been attacked by better people than them #MAGA pic.twitter.com/XtZW5PdU2b David A. Clarke, Jr. (@SheriffClarke) December 30, 2017He didn t stop there.BREAKING NEWS! When LYING LIB MEDIA makes up FAKE NEWS to smear me, the ANTIDOTE is go right at them. Punch them in the nose & MAKE THEM TASTE THEIR OWN BLOOD. Nothing gets a bully like LYING LIB MEDIA S attention better than to give them a taste of their own blood #neverbackdown pic.twitter.com/T2NY2psHCR David A. Clarke, Jr. (@SheriffClarke) December 30, 2017The internet called him out.This is your local newspaper and that search warrant isn t fake, and just because the chose not to file charges at the time doesn t mean they won t! Especially if you continue to lie. Months after decision not to charge Clarke, email search warrant filed https://t.co/zcbyc4Wp5b KeithLeBlanc (@KeithLeBlanc63) December 30, 2017I just hope the rest of the Village People aren t implicated. Kirk Ketchum (@kirkketchum) December 30, 2017Slaw, baked potatoes, or French fries? pic.twitter.com/fWfXsZupxy ALT- Immigration (@ALT_uscis) December 30, 2017pic.twitter.com/ymsOBLjfxU Pendulum Swinger (@PendulumSwngr) December 30, 2017you called your police friends to stand up for you when someone made fun of your hat Chris Jackson (@ChrisCJackson) December 30, 2017Is it me, with this masterful pshop of your hat, which I seem to never tire of. I think it s the steely resolve in your one visible eye pic.twitter.com/dWr5k8ZEZV Chris Mohney (@chrismohney) December 30, 2017Are you indicating with your fingers how many people died in your jail? I think you re a few fingers short, dipshit Ike Barinholtz (@ikebarinholtz) December 30, 2017ROFL. Internet tough guy with fake flair. pic.twitter.com/ulCFddhkdy KellMeCrazy (@Kel_MoonFace) December 30, 2017You re so edgy, buddy. Mrs. SMH (@MRSSMH2) December 30, 2017Is his break over at Applebees? Aaron (@feltrrr2) December 30, 2017Are you trying to earn your still relevant badge? CircusRebel (@CircusDrew) December 30, 2017make sure to hydrate, drink lots of water. It s rumored that prisoners can be denied water by prison officials. Robert Klinc (@RobertKlinc1) December 30, 2017Terrill Thomas, the 38-year-old black man who died of thirst in Clarke s Milwaukee County Jail cell this April, was a victim of homicide. We just thought we should point that out. It can t be repeated enough.Photo by Spencer Platt/Getty Images.",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name Coded Into His Website (IMAGES),"On Christmas day, Donald Trump announced that he would be back to work the following day, but he is golfing for the fourth day in a row. The former reality show star blasted former President Barack Obama for playing golf and now Trump is on track to outpace the number of golf games his predecessor played.Updated my tracker of Trump s appearances at Trump properties.71 rounds of golf including today s. At this pace, he ll pass Obama s first-term total by July 24 next year. https://t.co/Fg7VacxRtJ pic.twitter.com/5gEMcjQTbH Philip Bump (@pbump) December 29, 2017 That makes what a Washington Post reporter discovered on Trump s website really weird, but everything about this administration is bizarre AF. The coding contained a reference to Obama and golf: Unlike Obama, we are working to fix the problem and not on the golf course. However, the coding wasn t done correctly.The website of Donald Trump, who has spent several days in a row at the golf course, is coded to serve up the following message in the event of an internal server error: https://t.co/zrWpyMXRcz pic.twitter.com/wiQSQNNzw0 Christopher Ingraham (@_cingraham) December 28, 2017That snippet of code appears to be on all https://t.co/dkhw0AlHB4 pages, which the footer says is paid for by the RNC? pic.twitter.com/oaZDT126B3 Christopher Ingraham (@_cingraham) December 28, 2017It s also all over https://t.co/ayBlGmk65Z. As others have noted in this thread, this is weird code and it s not clear it would ever actually display, but who knows. Christopher Ingraham (@_cingraham) December 28, 2017After the coding was called out, the reference to Obama was deleted.UPDATE: The golf error message has been removed from the Trump and GOP websites. They also fixed the javascript = vs == problem. Still not clear when these messages would actually display, since the actual 404 (and presumably 500) page displays a different message pic.twitter.com/Z7dmyQ5smy Christopher Ingraham (@_cingraham) December 29, 2017That suggests someone at either RNC or the Trump admin is sensitive enough to Trump s golf problem to make this issue go away quickly once people noticed. You have no idea how much I d love to see the email exchange that led us here. Christopher Ingraham (@_cingraham) December 29, 2017 The code was f-cked up.The best part about this is that they are using the = (assignment) operator which means that bit of code will never get run. If you look a few lines up errorCode will always be 404 (@tw1trsux) December 28, 2017trump s coders can t code. Nobody is surprised. Tim Peterson (@timrpeterson) December 28, 2017Donald Trump is obsessed with Obama that his name was even in the coding of his website while he played golf again.Photo by Joe Raedle/Getty Images.",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump During His Christmas Speech,"Pope Francis used his annual Christmas Day message to rebuke Donald Trump without even mentioning his name. The Pope delivered his message just days after members of the United Nations condemned Trump s move to recognize Jerusalem as the capital of Israel. The Pontiff prayed on Monday for the peaceful coexistence of two states within mutually agreed and internationally recognized borders. We see Jesus in the children of the Middle East who continue to suffer because of growing tensions between Israelis and Palestinians, Francis said. On this festive day, let us ask the Lord for peace for Jerusalem and for all the Holy Land. Let us pray that the will to resume dialogue may prevail between the parties and that a negotiated solution can finally be reached. The Pope went on to plead for acceptance of refugees who have been forced from their homes, and that is an issue Trump continues to fight against. Francis used Jesus for which there was no place in the inn as an analogy. Today, as the winds of war are blowing in our world and an outdated model of development continues to produce human, societal and environmental decline, Christmas invites us to focus on the sign of the Child and to recognize him in the faces of little children, especially those for whom, like Jesus, there is no place in the inn, he said. Jesus knows well the pain of not being welcomed and how hard it is not to have a place to lay one s head, he added. May our hearts not be closed as they were in the homes of Bethlehem. The Pope said that Mary and Joseph were immigrants who struggled to find a safe place to stay in Bethlehem. They had to leave their people, their home, and their land, Francis said. This was no comfortable or easy journey for a young couple about to have a child. At heart, they were full of hope and expectation because of the child about to be born; yet their steps were weighed down by the uncertainties and dangers that attend those who have to leave their home behind. So many other footsteps are hidden in the footsteps of Joseph and Mary, Francis said Sunday. We see the tracks of entire families forced to set out in our own day. We see the tracks of millions of persons who do not choose to go away, but driven from their land, leave behind their dear ones. Amen to that.Photo by Christopher Furlong/Getty Images.",News,"December 25, 2017",0

## Text Preprocessing

In [9]:
# Display dataset information before preprocessing

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 44898 entries, 0 to 44897
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    44898 non-null  str
 1   text     44898 non-null  str
 2   subject  44898 non-null  str
 3   date     44898 non-null  str
 4   label    44898 non-null  int64
dtypes: int64(1), str(4)
memory usage: 112.3 MB

In [10]:
# Check missing values before preprocessing

df.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

## Convert Text to Lowercase

In [11]:
# Convert news text to lowercase
df["text"] = df["text"].str.lower()

print("Text converted to lowercase successfully.")

Text converted to lowercase successfully.

In [12]:
# Display first news article after lowercase conversion

df["text"].head(1)

0    donald trump just couldn t wish all americans a happy new year and leave it at that. instead, he had to give a shout out to his enemies, haters and  the very dishonest fake news media.  the former reality show star had just one job to do and he couldn t do it. as our country rapidly grows stronger and smarter, i want to wish all of my friends, supporters, enemies, haters, and even the very dishonest fake news media, a happy and healthy new year,  president angry pants tweeted.  2018 will be a great year for america! as our country rapidly grows stronger and smarter, i want to wish all of my friends, supporters, enemies, haters, and even the very dishonest fake news media, a happy and healthy new year. 2018 will be a great year for america!  donald j. trump (@realdonaldtrump) december 31, 2017trump s tweet went down about as welll as you d expect.what kind of president sends a new year s greeting like this despicable, petty, infantile gibberish? only trump! his lack of decency won t even allow him to rise above the gutter long enough to wish the american citizens a happy new year!  bishop talbert swan (@talbertswan) december 31, 2017no one likes you  calvin (@calvinstowell) december 31, 2017your impeachment would make 2018 a great year for america, but i ll also accept regaining control of congress.  miranda yaver (@mirandayaver) december 31, 2017do you hear yourself talk? when you have to include that many people that hate you you have to wonder? why do the they all hate me?  alan sandoval (@alansandoval13) december 31, 2017who uses the word haters in a new years wish??  marlene (@marlene399) december 31, 2017you can t just say happy new year?  koren pollitt (@korencarpenter) december 31, 2017here s trump s new year s eve tweet from 2016.happy new year to all, including to my many enemies and those who have fought me and lost so badly they just don t know what to do. love!  donald j. trump (@realdonaldtrump) december 31, 2016this is nothing new for trump. he s been doing this for years.trump has directed messages to his  enemies  and  haters  for new year s, easter, thanksgiving, and the anniversary of 9/11. pic.twitter.com/4fpae2kypa  daniel dale (@ddale8) december 31, 2017trump s holiday tweets are clearly not presidential.how long did he work at hallmark before becoming president?  steven goodine (@sgoodine) december 31, 2017he s always been like this . . . the only difference is that in the last few years, his filter has been breaking down.  roy schulze (@thbthttt) december 31, 2017who, apart from a teenager uses the term haters?  wendy (@wendywhistles) december 31, 2017he s a fucking 5 year old  who knows (@rainyday80) december 31, 2017so, to all the people who voted for this a hole thinking he would change once he got into power, you were wrong! 70-year-old men don t change and now he s a year older.photo by andrew burton/getty images.
Name: text, dtype: str

## Convert News Title to Lowercase

In [13]:
# Convert news title to lowercase
df["title"] = df["title"].str.lower()

print("Title converted to lowercase successfully.")

Title converted to lowercase successfully.

In [14]:
# Display first news title after lowercase conversion

df["title"].head(1)

0     donald trump sends out embarrassing new year’s eve message; this is disturbing
Name: title, dtype: str

## Remove HTML Tags

In [15]:
# Import BeautifulSoup
from bs4 import BeautifulSoup

In [16]:
# Create a function to remove HTML tags
def remove_html(text):
    return BeautifulSoup(str(text), "html.parser").get_text()

In [17]:
# Remove HTML tags from news text
df["text"] = df["text"].apply(remove_html)

print("HTML tags removed successfully from text.")

HTML tags removed successfully from text.

In [18]:
# Remove HTML tags from news title

df["title"] = df["title"].apply(remove_html)

print("HTML tags removed successfully from title.")

HTML tags removed successfully from title.

In [19]:
# Display the first news article after HTML tag removal

df["text"].head(1)

0    donald trump just couldn t wish all americans a happy new year and leave it at that. instead, he had to give a shout out to his enemies, haters and  the very dishonest fake news media.  the former reality show star had just one job to do and he couldn t do it. as our country rapidly grows stronger and smarter, i want to wish all of my friends, supporters, enemies, haters, and even the very dishonest fake news media, a happy and healthy new year,  president angry pants tweeted.  2018 will be a great year for america! as our country rapidly grows stronger and smarter, i want to wish all of my friends, supporters, enemies, haters, and even the very dishonest fake news media, a happy and healthy new year. 2018 will be a great year for america!  donald j. trump (@realdonaldtrump) december 31, 2017trump s tweet went down about as welll as you d expect.what kind of president sends a new year s greeting like this despicable, petty, infantile gibberish? only trump! his lack of decency won t even allow him to rise above the gutter long enough to wish the american citizens a happy new year!  bishop talbert swan (@talbertswan) december 31, 2017no one likes you  calvin (@calvinstowell) december 31, 2017your impeachment would make 2018 a great year for america, but i ll also accept regaining control of congress.  miranda yaver (@mirandayaver) december 31, 2017do you hear yourself talk? when you have to include that many people that hate you you have to wonder? why do the they all hate me?  alan sandoval (@alansandoval13) december 31, 2017who uses the word haters in a new years wish??  marlene (@marlene399) december 31, 2017you can t just say happy new year?  koren pollitt (@korencarpenter) december 31, 2017here s trump s new year s eve tweet from 2016.happy new year to all, including to my many enemies and those who have fought me and lost so badly they just don t know what to do. love!  donald j. trump (@realdonaldtrump) december 31, 2016this is nothing new for trump. he s been doing this for years.trump has directed messages to his  enemies  and  haters  for new year s, easter, thanksgiving, and the anniversary of 9/11. pic.twitter.com/4fpae2kypa  daniel dale (@ddale8) december 31, 2017trump s holiday tweets are clearly not presidential.how long did he work at hallmark before becoming president?  steven goodine (@sgoodine) december 31, 2017he s always been like this . . . the only difference is that in the last few years, his filter has been breaking down.  roy schulze (@thbthttt) december 31, 2017who, apart from a teenager uses the term haters?  wendy (@wendywhistles) december 31, 2017he s a fucking 5 year old  who knows (@rainyday80) december 31, 2017so, to all the people who voted for this a hole thinking he would change once he got into power, you were wrong! 70-year-old men don t change and now he s a year older.photo by andrew burton/getty images.
Name: text, dtype: str

## Remove URLs

In [20]:
# Create a function to remove URLs
def remove_url(text):
    return re.sub(r'https?://\S+|www\.\S+', '', str(text))

In [21]:
# Remove URLs from news text
df["text"] = df["text"].apply(remove_url)

print("URLs removed successfully from text.")

URLs removed successfully from text.

In [22]:
# Remove URLs from news title
df["title"] = df["title"].apply(remove_url)

print("URLs removed successfully from title.")

URLs removed successfully from title.

In [23]:
# Display the first news article after URL removal

df["text"].head(1)

0    donald trump just couldn t wish all americans a happy new year and leave it at that. instead, he had to give a shout out to his enemies, haters and  the very dishonest fake news media.  the former reality show star had just one job to do and he couldn t do it. as our country rapidly grows stronger and smarter, i want to wish all of my friends, supporters, enemies, haters, and even the very dishonest fake news media, a happy and healthy new year,  president angry pants tweeted.  2018 will be a great year for america! as our country rapidly grows stronger and smarter, i want to wish all of my friends, supporters, enemies, haters, and even the very dishonest fake news media, a happy and healthy new year. 2018 will be a great year for america!  donald j. trump (@realdonaldtrump) december 31, 2017trump s tweet went down about as welll as you d expect.what kind of president sends a new year s greeting like this despicable, petty, infantile gibberish? only trump! his lack of decency won t even allow him to rise above the gutter long enough to wish the american citizens a happy new year!  bishop talbert swan (@talbertswan) december 31, 2017no one likes you  calvin (@calvinstowell) december 31, 2017your impeachment would make 2018 a great year for america, but i ll also accept regaining control of congress.  miranda yaver (@mirandayaver) december 31, 2017do you hear yourself talk? when you have to include that many people that hate you you have to wonder? why do the they all hate me?  alan sandoval (@alansandoval13) december 31, 2017who uses the word haters in a new years wish??  marlene (@marlene399) december 31, 2017you can t just say happy new year?  koren pollitt (@korencarpenter) december 31, 2017here s trump s new year s eve tweet from 2016.happy new year to all, including to my many enemies and those who have fought me and lost so badly they just don t know what to do. love!  donald j. trump (@realdonaldtrump) december 31, 2016this is nothing new for trump. he s been doing this for years.trump has directed messages to his  enemies  and  haters  for new year s, easter, thanksgiving, and the anniversary of 9/11. pic.twitter.com/4fpae2kypa  daniel dale (@ddale8) december 31, 2017trump s holiday tweets are clearly not presidential.how long did he work at hallmark before becoming president?  steven goodine (@sgoodine) december 31, 2017he s always been like this . . . the only difference is that in the last few years, his filter has been breaking down.  roy schulze (@thbthttt) december 31, 2017who, apart from a teenager uses the term haters?  wendy (@wendywhistles) december 31, 2017he s a fucking 5 year old  who knows (@rainyday80) december 31, 2017so, to all the people who voted for this a hole thinking he would change once he got into power, you were wrong! 70-year-old men don t change and now he s a year older.photo by andrew burton/getty images.
Name: text, dtype: str

## Remove Punctuation

In [24]:
# Create a function to remove punctuation
def remove_punctuation(text):
    return text.translate(str.maketrans("", "", string.punctuation))

In [25]:
# Remove punctuation from news text
df["text"] = df["text"].apply(remove_punctuation)

print("Punctuation removed successfully from text.")

Punctuation removed successfully from text.

In [26]:
# Remove punctuation from news title
df["title"] = df["title"].apply(remove_punctuation)

print("Punctuation removed successfully from title.")

Punctuation removed successfully from title.

In [27]:
# Display the first news article after punctuation removal

df["text"].head(1)

0    donald trump just couldn t wish all americans a happy new year and leave it at that instead he had to give a shout out to his enemies haters and  the very dishonest fake news media  the former reality show star had just one job to do and he couldn t do it as our country rapidly grows stronger and smarter i want to wish all of my friends supporters enemies haters and even the very dishonest fake news media a happy and healthy new year  president angry pants tweeted  2018 will be a great year for america as our country rapidly grows stronger and smarter i want to wish all of my friends supporters enemies haters and even the very dishonest fake news media a happy and healthy new year 2018 will be a great year for america  donald j trump realdonaldtrump december 31 2017trump s tweet went down about as welll as you d expectwhat kind of president sends a new year s greeting like this despicable petty infantile gibberish only trump his lack of decency won t even allow him to rise above the gutter long enough to wish the american citizens a happy new year  bishop talbert swan talbertswan december 31 2017no one likes you  calvin calvinstowell december 31 2017your impeachment would make 2018 a great year for america but i ll also accept regaining control of congress  miranda yaver mirandayaver december 31 2017do you hear yourself talk when you have to include that many people that hate you you have to wonder why do the they all hate me  alan sandoval alansandoval13 december 31 2017who uses the word haters in a new years wish  marlene marlene399 december 31 2017you can t just say happy new year  koren pollitt korencarpenter december 31 2017here s trump s new year s eve tweet from 2016happy new year to all including to my many enemies and those who have fought me and lost so badly they just don t know what to do love  donald j trump realdonaldtrump december 31 2016this is nothing new for trump he s been doing this for yearstrump has directed messages to his  enemies  and  haters  for new year s easter thanksgiving and the anniversary of 911 pictwittercom4fpae2kypa  daniel dale ddale8 december 31 2017trump s holiday tweets are clearly not presidentialhow long did he work at hallmark before becoming president  steven goodine sgoodine december 31 2017he s always been like this    the only difference is that in the last few years his filter has been breaking down  roy schulze thbthttt december 31 2017who apart from a teenager uses the term haters  wendy wendywhistles december 31 2017he s a fucking 5 year old  who knows rainyday80 december 31 2017so to all the people who voted for this a hole thinking he would change once he got into power you were wrong 70yearold men don t change and now he s a year olderphoto by andrew burtongetty images
Name: text, dtype: str

## Remove Numbers

In [28]:
# Create a function to remove numbers
def remove_numbers(text):
    return re.sub(r"\d+", "", str(text))

In [29]:
# Remove numbers from news text
df["text"] = df["text"].apply(remove_numbers)

print("Numbers removed successfully from text.")

Numbers removed successfully from text.

In [30]:
# Remove numbers from news title
df["title"] = df["title"].apply(remove_numbers)

print("Numbers removed successfully from title.")

Numbers removed successfully from title.

In [31]:
# Display the first news article after number removal

df["text"].head(1)

0    donald trump just couldn t wish all americans a happy new year and leave it at that instead he had to give a shout out to his enemies haters and  the very dishonest fake news media  the former reality show star had just one job to do and he couldn t do it as our country rapidly grows stronger and smarter i want to wish all of my friends supporters enemies haters and even the very dishonest fake news media a happy and healthy new year  president angry pants tweeted   will be a great year for america as our country rapidly grows stronger and smarter i want to wish all of my friends supporters enemies haters and even the very dishonest fake news media a happy and healthy new year  will be a great year for america  donald j trump realdonaldtrump december  trump s tweet went down about as welll as you d expectwhat kind of president sends a new year s greeting like this despicable petty infantile gibberish only trump his lack of decency won t even allow him to rise above the gutter long enough to wish the american citizens a happy new year  bishop talbert swan talbertswan december  no one likes you  calvin calvinstowell december  your impeachment would make  a great year for america but i ll also accept regaining control of congress  miranda yaver mirandayaver december  do you hear yourself talk when you have to include that many people that hate you you have to wonder why do the they all hate me  alan sandoval alansandoval december  who uses the word haters in a new years wish  marlene marlene december  you can t just say happy new year  koren pollitt korencarpenter december  here s trump s new year s eve tweet from happy new year to all including to my many enemies and those who have fought me and lost so badly they just don t know what to do love  donald j trump realdonaldtrump december  this is nothing new for trump he s been doing this for yearstrump has directed messages to his  enemies  and  haters  for new year s easter thanksgiving and the anniversary of  pictwittercomfpaekypa  daniel dale ddale december  trump s holiday tweets are clearly not presidentialhow long did he work at hallmark before becoming president  steven goodine sgoodine december  he s always been like this    the only difference is that in the last few years his filter has been breaking down  roy schulze thbthttt december  who apart from a teenager uses the term haters  wendy wendywhistles december  he s a fucking  year old  who knows rainyday december  so to all the people who voted for this a hole thinking he would change once he got into power you were wrong yearold men don t change and now he s a year olderphoto by andrew burtongetty images
Name: text, dtype: str

## Remove Special Characters

In [32]:
# Create a function to remove special characters

def remove_special_characters(text):
    return re.sub(r"[^a-zA-Z\s]", "", str(text))

In [33]:
# Remove special characters from news text

df["text"] = df["text"].apply(remove_special_characters)

print("Special characters removed successfully from text.")

Special characters removed successfully from text.

In [34]:
# Remove special characters from news title

df["title"] = df["title"].apply(remove_special_characters)

print("Special characters removed successfully from title.")

Special characters removed successfully from title.

In [35]:
# Display the first news article after removing special characters

df["text"].head(1)

0    donald trump just couldn t wish all americans a happy new year and leave it at that instead he had to give a shout out to his enemies haters and  the very dishonest fake news media  the former reality show star had just one job to do and he couldn t do it as our country rapidly grows stronger and smarter i want to wish all of my friends supporters enemies haters and even the very dishonest fake news media a happy and healthy new year  president angry pants tweeted   will be a great year for america as our country rapidly grows stronger and smarter i want to wish all of my friends supporters enemies haters and even the very dishonest fake news media a happy and healthy new year  will be a great year for america  donald j trump realdonaldtrump december  trump s tweet went down about as welll as you d expectwhat kind of president sends a new year s greeting like this despicable petty infantile gibberish only trump his lack of decency won t even allow him to rise above the gutter long enough to wish the american citizens a happy new year  bishop talbert swan talbertswan december  no one likes you  calvin calvinstowell december  your impeachment would make  a great year for america but i ll also accept regaining control of congress  miranda yaver mirandayaver december  do you hear yourself talk when you have to include that many people that hate you you have to wonder why do the they all hate me  alan sandoval alansandoval december  who uses the word haters in a new years wish  marlene marlene december  you can t just say happy new year  koren pollitt korencarpenter december  here s trump s new year s eve tweet from happy new year to all including to my many enemies and those who have fought me and lost so badly they just don t know what to do love  donald j trump realdonaldtrump december  this is nothing new for trump he s been doing this for yearstrump has directed messages to his  enemies  and  haters  for new year s easter thanksgiving and the anniversary of  pictwittercomfpaekypa  daniel dale ddale december  trump s holiday tweets are clearly not presidentialhow long did he work at hallmark before becoming president  steven goodine sgoodine december  he s always been like this    the only difference is that in the last few years his filter has been breaking down  roy schulze thbthttt december  who apart from a teenager uses the term haters  wendy wendywhistles december  he s a fucking  year old  who knows rainyday december  so to all the people who voted for this a hole thinking he would change once he got into power you were wrong yearold men don t change and now he s a year olderphoto by andrew burtongetty images
Name: text, dtype: str

## Remove Extra Spaces

In [36]:
# Create a function to remove extra spaces

def remove_extra_spaces(text):
    return re.sub(r"\s+", " ", str(text)).strip()

In [37]:
# Remove extra spaces from news text

df["text"] = df["text"].apply(remove_extra_spaces)

print("Extra spaces removed successfully from text.")

Extra spaces removed successfully from text.

In [38]:
# Remove extra spaces from news title

df["title"] = df["title"].apply(remove_extra_spaces)

print("Extra spaces removed successfully from title.")

Extra spaces removed successfully from title.

In [39]:
# Display the first news article after removing extra spaces

df["text"].head(1)

0    donald trump just couldn t wish all americans a happy new year and leave it at that instead he had to give a shout out to his enemies haters and the very dishonest fake news media the former reality show star had just one job to do and he couldn t do it as our country rapidly grows stronger and smarter i want to wish all of my friends supporters enemies haters and even the very dishonest fake news media a happy and healthy new year president angry pants tweeted will be a great year for america as our country rapidly grows stronger and smarter i want to wish all of my friends supporters enemies haters and even the very dishonest fake news media a happy and healthy new year will be a great year for america donald j trump realdonaldtrump december trump s tweet went down about as welll as you d expectwhat kind of president sends a new year s greeting like this despicable petty infantile gibberish only trump his lack of decency won t even allow him to rise above the gutter long enough to wish the american citizens a happy new year bishop talbert swan talbertswan december no one likes you calvin calvinstowell december your impeachment would make a great year for america but i ll also accept regaining control of congress miranda yaver mirandayaver december do you hear yourself talk when you have to include that many people that hate you you have to wonder why do the they all hate me alan sandoval alansandoval december who uses the word haters in a new years wish marlene marlene december you can t just say happy new year koren pollitt korencarpenter december here s trump s new year s eve tweet from happy new year to all including to my many enemies and those who have fought me and lost so badly they just don t know what to do love donald j trump realdonaldtrump december this is nothing new for trump he s been doing this for yearstrump has directed messages to his enemies and haters for new year s easter thanksgiving and the anniversary of pictwittercomfpaekypa daniel dale ddale december trump s holiday tweets are clearly not presidentialhow long did he work at hallmark before becoming president steven goodine sgoodine december he s always been like this the only difference is that in the last few years his filter has been breaking down roy schulze thbthttt december who apart from a teenager uses the term haters wendy wendywhistles december he s a fucking year old who knows rainyday december so to all the people who voted for this a hole thinking he would change once he got into power you were wrong yearold men don t change and now he s a year olderphoto by andrew burtongetty images
Name: text, dtype: str

## Tokenization

In [40]:
# Import NLTK
import nltk

In [41]:
# Download punkt tokenizer

nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to C:\Users\MY
[nltk_data]     PC\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\MY
[nltk_data]     PC\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [42]:

# Import word_tokenize
from nltk.tokenize import word_tokenize

In [43]:
# Tokenize the news text
df["tokens"] = df["text"].apply(word_tokenize)

print("Text tokenization completed successfully.")

Text tokenization completed successfully.

In [44]:
# Display tokens of the first news article

df["tokens"].head(1)

0    [donald, trump, just, couldn, t, wish, all, americans, a, happy, new, year, and, leave, it, at, that, instead, he, had, to, give, a, shout, out, to, his, enemies, haters, and, the, very, dishonest, fake, news, media, the, former, reality, show, star, had, just, one, job, to, do, and, he, couldn, t, do, it, as, our, country, rapidly, grows, stronger, and, smarter, i, want, to, wish, all, of, my, friends, supporters, enemies, haters, and, even, the, very, dishonest, fake, news, media, a, happy, and, healthy, new, year, president, angry, pants, tweeted, will, be, a, great, year, for, america, as, our, country, ...]
Name: tokens, dtype: object

## Stopword Removal

In [45]:
# Download stopwords

nltk.download("stopwords")

[nltk_data] Downloading package stopwords to C:\Users\MY
[nltk_data]     PC\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [46]:
# Import stopwords
from nltk.corpus import stopwords

In [47]:
# Store English stopwords
stop_words = set(stopwords.words("english"))

In [48]:
# Remove stopwords from tokens
df["tokens"] = df["tokens"].apply(
    lambda words: [word for word in words if word not in stop_words]
)
print("Stopwords removed successfully.")

Stopwords removed successfully.

In [49]:
# Display tokens after stopword removal

df["tokens"].head(1)

0    [donald, trump, wish, americans, happy, new, year, leave, instead, give, shout, enemies, haters, dishonest, fake, news, media, former, reality, show, star, one, job, country, rapidly, grows, stronger, smarter, want, wish, friends, supporters, enemies, haters, even, dishonest, fake, news, media, happy, healthy, new, year, president, angry, pants, tweeted, great, year, america, country, rapidly, grows, stronger, smarter, want, wish, friends, supporters, enemies, haters, even, dishonest, fake, news, media, happy, healthy, new, year, great, year, america, donald, j, trump, realdonaldtrump, december, trump, tweet, went, welll, expectwhat, kind, president, sends, new, year, greeting, like, despicable, petty, infantile, gibberish, trump, lack, decency, even, allow, rise, ...]
Name: tokens, dtype: object

## Lemmatization using spaCy

In [50]:
# Import spaCy
import spacy

In [51]:
# Load English language model
nlp = spacy.load("en_core_web_sm")

print("spaCy model loaded successfully.")

spaCy model loaded successfully.

In [52]:
# Create a function for Lemmatization

def lemmatize_text(tokens):
    doc = nlp(" ".join(tokens))
    return [token.lemma_ for token in doc]

In [53]:
tokens = ["this", "is", "a", "test"]
print(lemmatize_text(tokens))

['this', 'be', 'a', 'test']

In [54]:
# Apply Lemmatization using spaCy nlp.pipe 
docs = nlp.pipe(
    (" ".join(tokens) for tokens in df["tokens"]),
    batch_size=100
)

df["tokens"] = [
    [token.lemma_ for token in doc]
    for doc in docs
]

print("Lemmatization completed successfully.")

# Apply lemmatization
#df["tokens"] = df["tokens"].apply(lemmatize_text)

#print("Lemmatization completed successfully.")

Lemmatization completed successfully.

In [55]:
# Display lemmatized tokens
df["tokens"].head(1)

0    [donald, trump, wish, americans, happy, new, year, leave, instead, give, shout, enemy, hater, dishonest, fake, news, medium, former, reality, show, star, one, job, country, rapidly, grow, strong, smart, want, wish, friend, supporter, enemy, hater, even, dishonest, fake, news, medium, happy, healthy, new, year, president, angry, pant, tweet, great, year, america, country, rapidly, grow, strong, smart, want, wish, friend, supporter, enemy, hater, even, dishonest, fake, news, medium, happy, healthy, new, year, great, year, america, donald, j, trump, realdonaldtrump, december, trump, tweet, go, welll, expectwhat, kind, president, send, new, year, greeting, like, despicable, petty, infantile, gibberish, trump, lack, decency, even, allow, rise, ...]
Name: tokens, dtype: object

## Create Clean Text

In [56]:
# Join tokens to create clean text
df["clean_text"] = df["tokens"].apply(lambda words: " ".join(words))

print("Clean text created successfully.")

Clean text created successfully.

In [57]:
# Compare original and cleaned text
df[["text", "clean_text"]].head()

,text,clean_text
0,donald trump just couldn t wish all americans a happy new year and leave it at that instead he had to give a shout out to his enemies haters and the very dishonest fake news media the former reality show star had just one job to do and he couldn t do it as our country rapidly grows stronger and smarter i want to wish all of my friends supporters enemies haters and even the very dishonest fake news media a happy and healthy new year president angry pants tweeted will be a great year for america as our country rapidly grows stronger and smarter i want to wish all of my friends supporters enemies haters and even the very dishonest fake news media a happy and healthy new year will be a great year for america donald j trump realdonaldtrump december trump s tweet went down about as welll as you d expectwhat kind of president sends a new year s greeting like this despicable petty infantile gibberish only trump his lack of decency won t even allow him to rise above the gutter long enough to wish the american citizens a happy new year bishop talbert swan talbertswan december no one likes you calvin calvinstowell december your impeachment would make a great year for america but i ll also accept regaining control of congress miranda yaver mirandayaver december do you hear yourself talk when you have to include that many people that hate you you have to wonder why do the they all hate me alan sandoval alansandoval december who uses the word haters in a new years wish marlene marlene december you can t just say happy new year koren pollitt korencarpenter december here s trump s new year s eve tweet from happy new year to all including to my many enemies and those who have fought me and lost so badly they just don t know what to do love donald j trump realdonaldtrump december this is nothing new for trump he s been doing this for yearstrump has directed messages to his enemies and haters for new year s easter thanksgiving and the anniversary of pictwittercomfpaekypa daniel dale ddale december trump s holiday tweets are clearly not presidentialhow long did he work at hallmark before becoming president steven goodine sgoodine december he s always been like this the only difference is that in the last few years his filter has been breaking down roy schulze thbthttt december who apart from a teenager uses the term haters wendy wendywhistles december he s a fucking year old who knows rainyday december so to all the people who voted for this a hole thinking he would change once he got into power you were wrong yearold men don t change and now he s a year olderphoto by andrew burtongetty images,donald trump wish americans happy new year leave instead give shout enemy hater dishonest fake news medium former reality show star one job country rapidly grow strong smart want wish friend supporter enemy hater even dishonest fake news medium happy healthy new year president angry pant tweet great year america country rapidly grow strong smart want wish friend supporter enemy hater even dishonest fake news medium happy healthy new year great year america donald j trump realdonaldtrump december trump tweet go welll expectwhat kind president send new year greeting like despicable petty infantile gibberish trump lack decency even allow rise gutter long enough wish american citizen happy new year bishop talbert swan talbertswan december one like calvin calvinstowell december impeachment would make great year america also accept regain control congress miranda yaver mirandayaver december hear talk include many people hate wonder hate alan sandoval alansandoval december use word hater new year wish marlene marlene december say happy new year koren pollitt korencarpenter december trump new year eve tweet happy new year include many enemy fight lose badly know love donald j trump realdonaldtrump december nothing new trump yearstrump direct message enemy hater new year easter thanksgive anniversary pictwittercomfpaekypa daniel dale ddale december trump holiday tweet clearly presidentialhow long work hallmark become president steven goodine sgoodine december always like difference last year filter break roy schulze thbthttt december apart teenager use term hater wendy wendywhistle december fucking year old know rainyday december people vote hole thinking would change get power wrong yearold man change year olderphoto andrew burtongetty image
1,house intelligence committee chairman devin nunes is going to have a bad day he s been under the assumption like many of us that the christopher steeledossier was what prompted the russia investigation so he s been lashing out at the department of justice and the fbi in order to protect trump as it happens the dossier is not what started the investigation according to documents obtained by the new york timesformer trump campaign adviser george papadopoulos was drunk in a wine bar when he revealed knowledge of russian opposition research on hillary clintonon top of that papadopoulos wasn t just a covfefe boy for trump as his administration has alleged he had a much larger role but none so damning as being a drunken fool in a wine bar coffee boys don t help to arrange a new york meeting between trump and president abdel fattah elsisi of egypt two months before the election it was known before that the former aide set up meetings with world leaders for trump but team trump ran with him being merely a coffee boyin may papadopoulos revealed to australian diplomat alexander downer that russian officials were shopping around possible dirt on thendemocratic presidential nominee hillary clinton exactly how much mr papadopoulos said that night at the kensington wine rooms with the australian alexander downer is unclear the report states but two months later when leaked democratic emails began appearing online australian officials passed the information about mr papadopoulos to their american counterparts according to four current and former american and foreign officials with direct knowledge of the australians role papadopoulos pleaded guilty to lying to the fbi and is now a cooperating witness with special counsel robert mueller s teamthis isn t a presidency it s a badly scripted reality tv showphoto by win mcnameegetty images,house intelligence committee chairman devin nune go bad day assumption like many us christopher steeledossier prompt russia investigation lash department justice fbi order protect trump happen dossier start investigation accord document obtain new york timesformer trump campaign adviser george papadopoulos drunk wine bar reveal knowledge russian opposition research hillary clintonon top papadopoulos covfefe boy trump administration allege much large role none damn drunken fool wine bar coffee boy help arrange new york meeting trump president abdel fattah elsisi egypt two month election know former aide set meeting world leader trump team trump run merely coffee boyin may papadopoulo reveal australian diplomat alexander downer russian official shop around possible dirt thendemocratic presidential nominee hillary clinton exactly much mr papadopoulos say night kensington wine room australian alexander downer unclear report state two month later leak democratic email begin appear online australian official pass information mr papadopoulos american counterpart accord four current former american foreign official direct knowledge australian role papadopoulo plead guilty lie fbi cooperate witness special counsel robert mueller teamthis presidency badly scripted reality tv showphoto win mcnameegetty image
2,on friday it was revealed that former milwaukee sheriff david clarke who was being considered for homeland security secretary in donald trump s administration has an email scandal of his ownin january there was a brief runin on a plane between clarke and fellow passenger dan black who he later had detained by the police for no reason whatsoever except that maybe his feelings were hurt clarke messaged the police to stop black after he deplaned and now a search warrant has been executed by the fbi to see the exchangesclarke is calling it fake news even though copies of the search warrant are on the internet i am unintimidated by lib media attempts to smear and discredit me with their fake news reports designed to silence me the former sheriff tweeted i will continue to poke them in the eye with a sharp stick and bitch slap these scum bags til they get it i have been attacked by better people than them maga i am unintimidated by lib media attempts to smear and discredit me with their fake news reports designed to silence me i will continue to poke them in the eye with a sharp stick and bitch slap these scum bags til they get it i have been attacked by better people than them maga pictwittercomxtzwpdub david a clarke jr sheriffclarke december he didn t stop therebreaking news when lying lib media makes up fake news to smear me the antidote is go right at them punch them in the nose make them taste their own blood nothing gets a bully like lying lib media s attention better than to give them a taste of their own blood neverbackdown pictwittercomtnypshcr david a clarke jr sheriffclarke december the internet called him outthis is your local newspaper and that search warrant isn t fake and just because the chose not to file charges at the time doesn t mean they won t especially if you continue to lie months after decision not to charge clarke email search warrant filed keithleblanc keithleblanc december i just hope the rest of the village people aren t implicated kirk ketchum kirkketchum december slaw baked potatoes or french fries pictwittercomfwfxszupxy alt immigration altuscis december pictwittercomymsobljfxu pendulum swinger pendulumswngr december you called your police friends to stand up for you when someone made fun of your hat chris jackson chriscjackson december is it me with this masterful pshop of your hat which i seem to never tire of i think it s the steely resolve in your one visible eye pictwittercomdwrkzezv chris mohney chrismohney december are you indicating with your fingers how many people died in your jail i think you re a few fingers short dipshit ike barinholtz ikebarinholtz december rofl internet tough guy with fake flair pictwittercomulcfddhkdy kellmecrazy kelmoonface december you re so edgy buddy mrs smh mrssmh december is his break over at applebees aaron feltrrr december are you trying to earn your still relevant badge circusrebel circusdrew december make sure to hydrate drink lots of water it s rumored that prisoners can be denied water by prison officials robert klinc robertklinc december terrill thomas the yearold black man who died of thirst in clarke s milwaukee county jail cell this april was a victim of homicide we just thought we should point that out it can t be repeated enoughphoto by spencer plattgetty images,friday reveal former milwaukee sheriff david clarke consider homeland security secretary donald trump administration email scandal ownin january brief runin plane clarke fellow passenger dan black later detain police reason whatsoever except maybe feeling hurt clarke message police stop black deplane search warrant execute fbi see exchangesclarke call fake news even though copy search warrant internet unintimidate lib medium attempt smear discredit fake news report design silence former sheriff tweet continue poke eye sharp stick bitch slap scum bag til get attack well people maga unintimidated lib medium attempt smear discredit fake news report design silence continue poke eye sharp stick bitch slap scum bag til get attack well people maga pictwittercomxtzwpdub david clarke jr sheriffclarke december stop therebreake news lie lib medium make fake news smear antidote go right punch nose make taste blood nothing get bully like lie lib medium attention well give taste blood neverbackdown pictwittercomtnypshcr david clarke jr sheriffclarke december internet call outthis local newspaper search warrant fake chose file charge time mean especially continue lie month decision charge clarke email search warrant file keithleblanc keithleblanc december hope rest village people implicate kirk ketchum kirkketchum december slaw bake potato french fry pictwittercomfwfxszupxy alt immigration altuscis december pictwittercomymsobljfxu pendulum swinger pendulumswngr december call police friend stand someone make fun hat chris jackson chriscjackson december masterful pshop hat seem never tire think steely resolve one visible eye pictwittercomdwrkzezv chris mohney chrismohney december indicate finger many people die jail think finger short dipshit ike barinholtz ikebarinholtz december rofl internet tough guy fake flair pictwittercomulcfddhkdy kellmecrazy kelmoonface december edgy buddy mrs smh mrssmh december break applebees aaron feltrrr december try earn still relevant badge circusrebel circusdrew december make sure hydrate drink lot water rumor prisoner deny water prison official robert klinc robertklinc december terrill thomas yearold black man die thirst clarke milwaukee county jail cell april victim homicide thought point repeat enoughphoto spencer plattgetty image
3,on christmas day donald trump announced that he would be back to work the following day but he is golfing for the fourth day in a row the former reality show star blasted former president barack obama for playing golf and now trump is on track to outpace the number of golf games his predecessor playedupdated my tracker of trump s appearances at trump properties rounds of golf including today s at this pace he ll pass obama s firstterm total by july next year pictwittercomgemcjqtbh philip bump pbump december that makes what a washington post reporter discovered on trump s website really weird but everything about this administration is bizarre af the coding contained a reference to obama and golf unlike obama we are working to fix the problem and not on the golf course however the coding wasn t done correctlythe website of donald trump who has spent several days in a row at the golf course is coded to serve up the following message in the event of an internal server error pictwittercomwiqsqnnzw christopher ingraham cingraham december that snippet of code appears to be on all pages which the footer says is paid for by the rnc pictwittercomoazdtb christopher ingraham cingraham december it s also all over as others have noted in this thread this is weird code and it s not clear it would ever actually display but who knows christopher ingraham cingraham december after the coding was called out the reference to obama was deletedupdate the golf error message has been removed from the trump and gop websites they also fixed the javascript vs problem still not clear when these messages would actually display since the actual and presumably page displays a different message pictwittercomzdmyqsmy christopher ingraham cingraham december that suggests someone at either rnc or the trump admin is sensitive enough to trump s golf problem to make this issue go away quickly once people noticed you have no idea how much i d love to see the email exchange that led us here christopher ingraham cingraham december the code was fcked upthe best part about this is that they are using the assignment operator which means that bit of code will never get run if you look a few lines up errorcode will always be twtrsux december trump s coders can t code nobody is surprised tim peterson timrpeterson december donald trump is obsessed with obama that his name was even in the coding of his website while he played golf againphoto by joe raedlegetty images,christmas day donald trump announce would back work follow day golf fourth day row former reality show star blast former president barack obama play golf trump track outpace number golf game predecessor playedupdate tracker trump appearance trump property round golf include today pace pass obama firstterm total july next year pictwittercomgemcjqtbh philip bump pbump december make washington post reporter discover trump website really weird everything administration bizarre af cod contain reference obama golf unlike obama work fix problem golf course however cod do correctlythe website donald trump spend several day row golf course cod serve follow message event internal server error pictwittercomwiqsqnnzw christopher ingraham cingraham december snippet code appear page footer say pay rnc pictwittercomoazdtb christopher ingraham cingraham december also other note thread weird code clear would ever actually display know christopher ingraham cingraham december coding call reference obama deletedupdate golf error message remove trump gop website also fix javascript vs problem still clear message would actually display since actual presumably page display different message pictwittercomzdmyqsmy christopher ingraham cingraham december suggest someone either rnc trump admin sensitive enough trump golf problem make issue go away quickly people notice idea much love see email exchange lead us christopher ingraham cingraham december code fcke upthe good part use assignment operator mean bit code never get run look line errorcode always twtrsux december trump coder code nobody surprise tim peterson timrpeterson december donald trump obsess obama name even cod website play golf againphoto joe raedlegetty image

In [58]:
# Display the first cleaned news article
df["clean_text"].head(1)

0    donald trump wish americans happy new year leave instead give shout enemy hater dishonest fake news medium former reality show star one job country rapidly grow strong smart want wish friend supporter enemy hater even dishonest fake news medium happy healthy new year president angry pant tweet great year america country rapidly grow strong smart want wish friend supporter enemy hater even dishonest fake news medium happy healthy new year great year america donald j trump realdonaldtrump december trump tweet go welll expectwhat kind president send new year greeting like despicable petty infantile gibberish trump lack decency even allow rise gutter long enough wish american citizen happy new year bishop talbert swan talbertswan december one like calvin calvinstowell december impeachment would make great year america also accept regain control congress miranda yaver mirandayaver december hear talk include many people hate wonder hate alan sandoval alansandoval december use word hater new year wish marlene marlene december say happy new year koren pollitt korencarpenter december trump new year eve tweet happy new year include many enemy fight lose badly know love donald j trump realdonaldtrump december nothing new trump yearstrump direct message enemy hater new year easter thanksgive anniversary pictwittercomfpaekypa daniel dale ddale december trump holiday tweet clearly presidentialhow long work hallmark become president steven goodine sgoodine december always like difference last year filter break roy schulze thbthttt december apart teenager use term hater wendy wendywhistle december fucking year old know rainyday december people vote hole thinking would change get power wrong yearold man change year olderphoto andrew burtongetty image
Name: clean_text, dtype: str

## Final Dataset Validation

In [59]:
# Display dataset information after preprocessing
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 44898 entries, 0 to 44897
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       44898 non-null  str
 1   text        44898 non-null  str
 2   subject     44898 non-null  str
 3   date        44898 non-null  str
 4   label       44898 non-null  int64
 5   tokens      44898 non-null  object
 6   clean_text  44898 non-null  str
dtypes: int64(1), object(1), str(5)
memory usage: 178.8+ MB

In [60]:
# Check missing values after preprocessing
df.isnull().sum()

title         0
text          0
subject       0
date          0
label         0
tokens        0
clean_text    0
dtype: int64

In [61]:
# Display the final dataset shape
print("Final Dataset Shape:", df.shape)

Final Dataset Shape: (44898, 7)

In [62]:
# Display sample records
df[["title", "clean_text", "label"]].sample(5, random_state=42)

,title,clean_text,label
22216,ben stein calls out th circuit court committed a coup dtat against the constitution,st century wire say ben stein reputable professor pepperdine university also hollywood fame appear tv show film ferris bueller day make provocative statement judge jeanine pirro show recently discuss halt impose president trump executive order travel stein refer judgement th circuit court washington state coup tat executive branch constitution stein go call judge seattle political puppet judiciary political pawn watch interview complete statement note stark contrast rhetoric leftist medium pundit neglect note court ever block presidential order immigration past discuss legal efficacy halt actual text executive orderread trump news st century wire trump filessupport work subscribe become member wiretv,0
27917,trump drops steve bannon from national security council,washington reuters us president donald trump remove chief strategist steve bannon national security council wednesday reverse controversial decision early year give political adviser unprecedented role security discussion trump overhaul nsc confirm white house official also elevate general joseph dunford chairman joint chiefs staff dan coats director national intelligence head we intelligence agency official say change move nsc back core function suppose also appear mark victory national security adviser hr mcmaster tell national security expert feel battle death bannon other white house staff vice president mike pence say bannon would continue play important role policy play shakeup routine natural evolution ensure national security council organize way well serve president resolve make difficult decision pence say fox news bannon say statement succeed return nsc back traditional role coordinate foreign policy rather run cited president barack obamas national security adviser susan rice advocate change susan rice operationalized nsc last administration put nsc ensure deoperationalized general mcmaster nsc back proper function say trump white house team grapple infighting intrigue hobble young presidency recent day several senior us foreign policy national security official say mechanism shape trump administration response press challenge syria north korea iran still place critic bannon role nsc say give much weight decisionmake someone lack foreign policy expertise bannon chief executive trump presidential campaign month lead election november respect represent trump america first nationalistic voice help fuel antiwashington fervor push president part way times mainstream republicans join trump administration bannon head breitbart news rightwing website we representative adam schiff rank democrat house representatives intelligence committee call shift nsc positive step help mcmaster gain control body politicize bannon involvement administration policy north korea china russia syria continue drift hope shakeup bring level strategic vision body say bannon removal nsc potential setback sphere influence trump white house voice major decision trump confidant say bannon remain influential ever still involve everything still full confidence president fair much stuff confidant say speak condition anonymity white house official say bannon long need nsc departure trump first national security adviser michael flynn flynn force resign feb contact russias ambassador united states sergei kislyak prior trump take office jan official say bannon place nsc originally check flynn attend one nscs regular meeting official dismiss question power struggle bannon mcmaster say share world view however two current national security official reject white house explanation note two month pass since flynns departure mcmaster say speak condition anonymity also duel bannon other direct access trump future deputy national security adviser kt mcfarland former fox news commentator intelligence director ezra cohenwatnick flynn appointee staffing decision trump prepare first facetoface meeting thursday friday chinese president xi jinping threat north koreas nuclear missile program key component talk bannon seat nscs principals committee group include secretary state defense rank aide take rick perry energy secretary charge oversee we nuclear weapon arsenal,1
25007,puerto rico expects us to lift jones act shipping restrictions,reuters puerto rico governor ricardo rossello say wednesday expect federal government waive jones act would lift restriction ship provide aid island devastate hurricane maria say speak member congress party support emergency waiver expect waive rossello say interview cnn note sevenday waiver hurricane irma much less devastating island tuesday trump administration say need waive shipping restriction help get fuel supply stormravage puerto rico say would nothing address island damage port main impediment ship waiver would allow puerto rico get help we ship ship bring aid critical particularly fuel say one consideration right priority get fuel diesel gasoline across island right enough fuel limited transportation logistic point course get fuel island go critical major function telecom hospital water run appropriately jones act require good ship we port carry american ownedandoperate ship us senator john mccain ask acting department homeland security secretary elaine duke tuesday grant emergency waiver law say puerto rican resident would pay least twice much food drinking water supply without waiver correct version story fix paragraph four show administration formally deny waiver request,1
1377,oops trump just accidentally confirmed he leaked israeli intelligence to russia video,monday donald trump embarrassed country accidentally reveal source extremely classify information leak russia early monthwhile speculate source information israel trump make thing crystal clear press conference prime minister benjamin netanyahu president pussygrabber explained never say israel conversation russian recipient leak information single time understand never mention word name israel trump say never mention conversation say trump say gesture reporter another story wrong never mention word israel may say word israel according report israeli intelligence official shout we counterpart leak informationnow accidentallyperhapsonpurpose confirm come fromwatch happen belowpresident trump say never mention word israel oval office meeting russian official cnn politic cnnpolitic may feature image via screengrab,0
32476,donald trump heads for scotland to reopen a golf resort,glasgow scotland reuter us presidential candidate go abroad sharpen foreign policy credential donald trump arrive scotland friday reopen golf resort presumptive republican nominee visit familys ancestral homeland showcase farflung business empire mother bear scotland isle lewis throng reporter watching make dramatic arrival helicopter seaside trump turnberry resort schedule news conference th hole noon et gmt visit turnberry follow stop resort aberdeen saturday allow comment outcome britain vote thursday whether remain european union do not think open golf resort get many foreign policy chop say saul anuzi former chairman michigan republican party since he s right middle eu vote may end pr bonanza risk realestate tycoon yet hold public office rate unfavorably percent americans opinion poll make foreign policy misstep time republican leader urge serious demeanor trump say would incline leave eu exchange insult british prime minister david cameron call new yorker antiimmigrant policy idea divisive wrong plan two meet trip baffle republican official say concentrate strengthen campaign take fight presumptive democratic nominee former us secretary state hillary clinton trump defeat crowded field opponent republican nomination face one controversy another late firing campaign manager week month party convention campaign get kind grow pain do not make sense would spend kind time go country say david yepsen director paul simon public policy institute southern illinois university turnberry story course open championship stag four time trump invest million renovate resort golf course scotland west coast km mile southw glasgow portray determination build course turnberry aberdeen overcome local opposition example type leadership skill americans would get win white house nov well scotland already united states trump write column press journal newspaper aberdeen aberdeen family oppose development threaten raise mexican flag reminder proposal build wall along us southern border keep immigrant enter illegally last republican presidential nominee former massachusetts governor mitt romney make gaffefille campaign trip london jerusalem poland,1

## Save Cleaned Dataset

In [63]:
# Save the cleaned dataset
df.to_csv("cleaned_data.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [64]:
# Verify the saved dataset
cleaned_df = pd.read_csv("cleaned_data.csv")

print(cleaned_df.shape)

(44898, 7)

## Data Preprocessing Summary

### Key Preprocessing Steps

- Loaded and merged Fake News and Real News datasets.
- Converted text and titles to lowercase.
- Removed HTML tags and URLs.
- Removed punctuation, numbers, and special characters.
- Removed extra spaces.
- Performed tokenization using NLTK.
- Removed English stopwords.
- Applied lemmatization using spaCy.
- Created a clean text column for NLP tasks.
- Saved the cleaned dataset for feature extraction and model training.

In [65]:
df["tokens"].head(1)

0    [donald, trump, wish, americans, happy, new, year, leave, instead, give, shout, enemy, hater, dishonest, fake, news, medium, former, reality, show, star, one, job, country, rapidly, grow, strong, smart, want, wish, friend, supporter, enemy, hater, even, dishonest, fake, news, medium, happy, healthy, new, year, president, angry, pant, tweet, great, year, america, country, rapidly, grow, strong, smart, want, wish, friend, supporter, enemy, hater, even, dishonest, fake, news, medium, happy, healthy, new, year, great, year, america, donald, j, trump, realdonaldtrump, december, trump, tweet, go, welll, expectwhat, kind, president, send, new, year, greeting, like, despicable, petty, infantile, gibberish, trump, lack, decency, even, allow, rise, ...]
Name: tokens, dtype: object